trigger: none

pr: none

schedules:
    - cron: 0,5,10 12 * * mon,tue,wed,fri
      displayName: Scheduled most mornings
      branches:
          include:
              - main #branch
      always: true

stages:
    - template: /pipeline-templates/e2e-stage-pipeline.yml
      parameters:
          env: someEnv

    - template: /pipeline-templates/e2e-stage-pipeline.yml
      parameters:
          env: someOtherEnv
