name: API Tests

on:
  schedule:
    - cron: '0,5,10 12 * * 1,2,3,5'  # At 12:00, 12:05, and 12:10 on Monday, Tuesday, Wednesday, and Friday
  push:
    branches:
      - main  # Run on every push to the main branch

jobs:
  test-someEnv:
    uses: ./.github/workflows/api-test-template.yml
    with:
      env: example

  test-someOtherEnv:
    uses: ./.github/workflows/api-test-template.yml
    with:
      env: someOtherEnv