name: API Test Template

on:
    workflow_call:
        inputs:
            env:
                required: true
                type: string

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Install Playwright
              run: npx playwright install chromium

            - name: Run API tests
              run: npm run test:api
              env:
                  CI: 'true'
                  SERVER: ${{ inputs.env }}

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report-${{ inputs.env }}
                  path: playwright-report/
                  retention-days: 2
